services:
  reserva-service:
    image: reserva-service
    restart: always
    environment:
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_RUNNING_IN_CONTAINER: "true"
      CN_CONECTION: "Server=bd;Port=3306;Database=ReservaCanchas;User=root;Password=fdbxmcphmq99kebb;AllowPublicKeyRetrieval=True;SslMode=None;ConnectionTimeout=30;"
      TZ: "America/Lima"
    expose:
      - "80"
    labels:
      - "traefik.enable=true"

      # HTTP
      - "traefik.http.routers.api.rule=Host(`canchas-back-qm3iu4-5efd82-38-242-128-50.traefik.me`)"
      - "traefik.http.routers.api.entrypoints=web"

      # HTTPS  🔴 ESTE ES EL QUE TE FALTA
      - "traefik.http.routers.api-secure.rule=Host(`canchas-back-qm3iu4-5efd82-38-242-128-50.traefik.me`)"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.tls.certresolver=letsencrypt"

      - "traefik.http.services.api.loadbalancer.server.port=80"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - reserva-service-log:/Logs
volumes:
    reserva-service-log:
        name: reserva-service-log