//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reserva.Domain.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("|", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese o escanee un código.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los Lotes {0} no fueron encontrados..
        /// </summary>
        public static string CodigosLoteNotFound {
            get {
                return ResourceManager.GetString("CodigosLoteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las muestras {0} no fueron encontradas. No es posible hacer un remuestreo. .
        /// </summary>
        public static string CodigosRandomNotFound {
            get {
                return ResourceManager.GetString("CodigosRandomNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al crear el registro.
        /// </summary>
        public static string CreateFailMessage {
            get {
                return ResourceManager.GetString("CreateFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue creado correctamente.
        /// </summary>
        public static string CreateSuccessMessage {
            get {
                return ResourceManager.GetString("CreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CustomMessage}.
        /// </summary>
        public static string CustomValidationMessage {
            get {
                return ResourceManager.GetString("CustomValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CustomMessage.
        /// </summary>
        public static string CustomValidationMessageArgument {
            get {
                return ResourceManager.GetString("CustomValidationMessageArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro a eliminar no fue encontrado.
        /// </summary>
        public static string DeleteRecordNotFound {
            get {
                return ResourceManager.GetString("DeleteRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue eliminado correctamente.
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue creado anteriormente.
        /// </summary>
        public static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Ruc ya fue registrado.
        /// </summary>
        public static string DuplicateRucRecord {
            get {
                return ResourceManager.GetString("DuplicateRucRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener como máximo {1} caracteres.
        /// </summary>
        public static string FieldMaxLength {
            get {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener como mínimo {1} caracteres.
        /// </summary>
        public static string FieldMinLength {
            get {
                return ResourceManager.GetString("FieldMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no fue encontrado.
        /// </summary>
        public static string GetRecordNotFound {
            get {
                return ResourceManager.GetString("GetRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información a procesar es requerida.
        /// </summary>
        public static string InformationRequired {
            get {
                return ResourceManager.GetString("InformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        public static byte[] logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string logoEmpresa {
            get {
                return ResourceManager.GetString("logoEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de página.
        /// </summary>
        public static string PageField {
            get {
                return ResourceManager.GetString("PageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de página debe ser mayor a 0.
        /// </summary>
        public static string PageFieldMinValue {
            get {
                return ResourceManager.GetString("PageFieldMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de Página.
        /// </summary>
        public static string PageSizeField {
            get {
                return ResourceManager.GetString("PageSizeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de página debe ser cómo máximo 1000.
        /// </summary>
        public static string PageSizeFieldMaxValue {
            get {
                return ResourceManager.GetString("PageSizeFieldMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de página debe ser mayor a 0.
        /// </summary>
        public static string PageSizeFieldMinValue {
            get {
                return ResourceManager.GetString("PageSizeFieldMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue creado anteriormente en Zona: {0}.
        /// </summary>
        public static string ProveedorDuplicadoZona {
            get {
                return ResourceManager.GetString("ProveedorDuplicadoZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error exportando el reporte.
        /// </summary>
        public static string ReportExportError {
            get {
                return ResourceManager.GetString("ReportExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de reporte no fue encontrado.
        /// </summary>
        public static string ReportFileDoesNotExist {
            get {
                return ResourceManager.GetString("ReportFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los parámetros de la búsqueda son requeridos.
        /// </summary>
        public static string SearchInformationRequired {
            get {
                return ResourceManager.GetString("SearchInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los parámetros de paginado de la búsqueda son requeridos.
        /// </summary>
        public static string SearchPageInformationRequired {
            get {
                return ResourceManager.GetString("SearchPageInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las direcciones de ordenamiento solo pueden ser &apos;asc&apos; o &apos;desc&apos;.
        /// </summary>
        public static string SortDirectionNotValid {
            get {
                return ResourceManager.GetString("SortDirectionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro a actualizar no fue encontrado.
        /// </summary>
        public static string UpdateRecordNotFound {
            get {
                return ResourceManager.GetString("UpdateRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro ya fue enviado.
        /// </summary>
        public static string UpdateRecordProcessSend {
            get {
                return ResourceManager.GetString("UpdateRecordProcessSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue actualizado correctamente.
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
    }
}
